services:
    actual_server:
        container_name: actual_server
        image: docker.io/actualbudget/actual-server:latest
        ports:
            - "5006:5006"
        volumes:
            - ./actual-data:/data
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "node src/scripts/health-check.js"]
            interval: 60s
            timeout: 10s
            retries: 3
            start_period: 20s

    ahaku-actual:
        container_name: ahaku-actual
        build: .
        env_file:
            - .env
        depends_on:
            actual_server:
                condition: service_healthy
